complete -c tailscode -l ask -d 'Open the question box, raising the running window first. Bind this to a key.'
complete -c tailscode -l connect -d 'Save a server by address and open it, without touching the setup screen.'
complete -c tailscode -l demo -d 'Open the scripted demo world: two sample servers, no tailnet, nothing real.'
complete -c tailscode -l force-desktop -d 'Render a build from .build/ on the real session anyway.'
complete -c tailscode -l help -d 'Print the usage summary and exit.'
complete -c tailscode -l name -d 'The name to file the server under, with --connect.'
complete -c tailscode -l opencode -d 'Treat the address given to --connect as an opencode server.'
complete -c tailscode -l password -d 'The servers password, with --connect. Prefer TAILSCODE_PASSWORD: an argument is readable by every process on the machine.'
complete -c tailscode -l probe-newchat -d 'Time the new-chat path end to end and print where it went.'
complete -c tailscode -l selftest -d 'Check the whole chain with no display, and exit non-zero on the first failure.'
complete -c tailscode -l themes -d 'Print every themes palette, as corrected, with each slots measured contrast.'
complete -c tailscode -l version -d 'Print the version and exit.'
