import TailscodeCore

/// The GTK client's answer to every capability in `CapabilityRegistry`. The switch is exhaustive
/// on purpose: a capability added to the registry refuses to compile this client until someone
/// decides what Linux does about it. One case per line, no `default` — `scripts/parity.sh`
/// parses this file and greps every anchor against `TailscodeLinux/Sources/TailscodeLinux/`.
enum ParityManifest {
    static let client = ParityClient.linux

    static func evidence(for capability: AppCapability) -> ParityEvidence {
        switch capability {
        case .sessionSections: return .implemented("groupIntoSections")
        case .sessionRowStatus: return .implemented("observedPresence")
        case .activityIconography: return .implemented("ActivityPulse")
        case .bulkSelection: return .implemented("SidebarSelectionBar")
        case .bulkSplit: return .implemented("openMarkedSplit")
        case .sessionPinning: return .implemented("pill-pinned")
        case .unreadTracking: return .implemented("toggleUnreadSelected")
        case .savedChats: return .implemented("SavedChatStore")
        case .archivedChats: return .implemented("ArchivedChatStore")
        case .deleteSession: return .implemented("deleteSession")
        case .renameSession: return .implemented("renameSession")
        case .forkSession: return .implemented("forkSession")
        case .transcriptSearch: return .implemented("runTranscriptSearch")
        case .listFilter: return .implemented("searchEntry")
        case .autoOpenLastSession: return .implemented("lastSession")
        case .liveListUpdates: return .implemented("SessionListStreaming")
        case .rowContextActions: return .implemented("rowMenuRows")
        case .rowSnippet: return .implemented("model.snippet")
        case .rowFacets: return .implemented("row-age")
        case .modelIdentityTint: return .implemented("modelLabel")
        case .usageGauges: return .implemented("usage-footer")
        case .quotaExhaustion: return .implemented("quotaNotice")
        case .quotaScoping: return .implemented("model-fact-spent")
        case .markdownRendering: return .implemented("PangoMarkdown")
        case .transcriptLinks: return .implemented("autolink")
        case .syntaxHighlighting: return .implemented("PangoSyntax")
        case .streamingGrowth: return .implemented("applyRows")
        case .streamCascade: return .implemented("CascadePainter")
        case .toolRows: return .implemented("ToolRowView")
        case .toolDiffs: return .implemented("ToolDiff")
        case .compactActivity: return .implemented("ToolRowView.makeRun")
        case .imageParts: return .implemented("ImageCache")
        case .imageViewer: return .implemented("ImageGallery")
        case .subagentCards: return .implemented("subagentRows")
        case .workflowCard: return .implemented("WorkflowCardView")
        case .taskBoard: return .implemented("TaskBoardView")
        case .questionCells: return .implemented("asksUserQuestion")
        case .compactionSeam: return .implemented("compaction")
        case .permissionCards: return .implemented("PendingCards")
        case .failureSurface: return .implemented("StatusBand")
        case .answerlessTurn: return .implemented("card-answerless")
        case .interruptedTurn: return .implemented("card-interrupted")
        case .authBanner: return .implemented("authBanner")
        case .followBottom: return .implemented("jumpToBottom")
        case .transcriptFind: return .implemented("findEntry")
        case .userEcho: return .implemented("echoedPrompt")
        case .vimComposer: return .implemented("VimEngine")
        case .slashCompletion: return .implemented("renderCompletion")
        case .slashDispatch: return .implemented("SlashDispatch.decide")
        case .commandCatalog: return .implemented("CommandCatalog")
        case .attachments: return .implemented("AttachmentIntake")
        case .drafts: return .implemented("DraftStore")
        case .sendQueue: return .implemented("sendButton")
        case .modelEffortPicker: return .implemented("modelRows")
        case .unifiedModelChooser: return .implemented("ModelChooserWindow")
        case .modelEffortDisplay: return .implemented("ModelBadge")
        case .ultracodeAura: return .implemented("AuraPainter")
        case .stopTurn: return .implemented("cancelCurrentTurn")
        case .statusBand: return .implemented("StatusBand")
        case .usagePanel: return .implemented("UsagePanel")
        case .usageAnalytics: return .implemented("AnalyticsCardRenderer")
        case .deepseekBalance: return .implemented("DeepSeekBalance")
        case .sessionSpend: return .implemented("SpendPanel")
        case .toasts: return .implemented("toastOverlay")
        case .serverManagement: return .implemented("ServerManager")
        case .tailnetDiscovery: return .implemented("DiscoveryPanel")
        case .connectDiagnosis: return .implemented("ConnectDiagnosis")
        case .serverSignIn: return .implemented("SignInDialog")
        case .serverSelfUpdate: return .implemented("renderSoftware")
        case .serverAutoUpdate: return .implemented("renderAutoUpdate")
        case .updateCenter: return .implemented("UpdatePanel")
        case .newChat: return .implemented("NewChatWindow")
        case .newChatPathCompletion: return .implemented("NewChatWindow")
        case .newChatDefaults: return .implemented("renderDefaults")
        case .newChatFailure: return .implemented("failureCard")
        case .keyboardShortcuts: return .implemented("installKeymap")
        case .shortcutCheatsheet: return .implemented("helpOverlay")
        case .fileBrowser: return .implemented("FileTree")
        case .gitState: return .implemented("GitPanel")
        case .terminalPane: return .implemented("TerminalPane")
        case .splitPanes: return .implemented("SplitHost")
        case .videoSlot: return .implemented("VideoPane")
        case .watchDirectory: return .implemented("WatchBoard.make")
        case .watchAccounts: return .implemented("WatchSignInDialog")
        case .browserSlot: return .implemented("WebPane")
        case .newPaneChooser: return .implemented("showChooser")
        case .chatDragToPane: return .implemented("acceptChatDrops")
        case .clickToActivate: return .implemented("onPressCapture")
        case .uiScale: return .implemented("UIScale")
        case .typeRamp: return .implemented("TypeCSS")
        case .themePicker: return .implemented("MatrixTheme")
        case .settingsSurface: return .implemented("Preferences")
        case .goalControl: return .implemented("goal-line")
        case .firstRunSetup: return .implemented("FirstRunDialog")
        case .tailscaleReadiness: return .implemented("TailscaleReading")
        case .demoMode: return .implemented("enterDemoMode")
        case .activityNotifications: return .implemented("Notifier")
        case .hapticFeedback: return .notApplicable("nothing under a desktop vibrates; a keyboard and a monitor have no actuator to drive, and the cues a phone gives a hand are carried here by the status band and the notifier")
        case .missedActivity: return .implemented("ActivityInbox.ordered")
        case .homeQuickActions: return .notApplicable("there is no springboard on a desktop to long-press; the app launches into its window, where every destination the phone's quick actions reach is already one click away")
        case .presenceOrb: return .implemented("OrbPainter")
        case .gameCenter: return .notApplicable("Game Center is Apple's account system, and this client cannot sign into it — there is no dashboard to open and nowhere to report a percentage; the trophies' arithmetic lives in Core, but a case with no account behind it would be a scoreboard nobody else can see, and the month's numbers are already usageAnalytics's parity")
        case .projectBoard: return .implemented("toggleProjectScope")
        case .quickAsk: return .implemented("QuickAskWindow")
        case .summonAnywhere: return .implemented("Summon")
        }
    }
}
