import TailscodeCore

/// The Mac's answer to every capability in `CapabilityRegistry`. The switch is exhaustive on
/// purpose: a capability added to the registry refuses to compile this client until someone
/// decides what the Mac does about it. One case per line, no `default` — `scripts/parity.sh`
/// parses this file and greps every anchor against `TailscodeMac/`.
enum ParityManifest {
    static let client = ParityClient.mac

    static func evidence(for capability: AppCapability) -> ParityEvidence {
        switch capability {
        case .sessionSections: return .implemented("groupIntoSections")
        case .sessionRowStatus: return .implemented("observedPresence")
        case .activityIconography: return .implemented("ActivityBadgeView")
        case .sessionPinning: return .implemented("menuTogglePinned")
        case .unreadTracking: return .implemented("markUnread")
        case .savedChats: return .implemented("SavedChatStore")
        case .archivedChats: return .implemented("ArchivedChatStore")
        case .deleteSession: return .implemented("deleteSession")
        case .bulkSelection: return .implemented("SidebarBulkBar")
        case .bulkSplit: return .implemented("openMarkedSplit")
        case .renameSession: return .implemented("renameSession")
        case .forkSession: return .implemented("forkSession")
        case .transcriptSearch: return .implemented("runTranscriptSearch")
        case .listFilter: return .implemented("searchField")
        case .autoOpenLastSession: return .implemented("lastSession")
        case .liveListUpdates: return .implemented("SessionListStreaming")
        case .rowContextActions: return .implemented("rowMenu")
        case .rowSnippet: return .implemented("if let snippet = model.snippet")
        case .rowFacets: return .implemented("detailText")
        case .modelIdentityTint: return .implemented("chipText")
        case .usageGauges: return .implemented("usageFooter")
        case .quotaExhaustion: return .implemented("quotaNotice")
        case .quotaScoping: return .implemented("quotasForModels")
        case .markdownRendering: return .implemented("MacMarkdown")
        case .transcriptLinks: return .implemented("extractBareLinks")
        case .syntaxHighlighting: return .implemented("RowKit.code")
        case .streamingGrowth: return .implemented("applyRows")
        case .streamCascade: return .implemented("CascadePainter")
        case .toolRows: return .implemented("ToolRowView")
        case .toolDiffs: return .implemented("ToolDiff")
        case .compactActivity: return .implemented("ToolRowView.makeRun")
        case .imageParts: return .implemented("ImageStore")
        case .imageViewer: return .implemented("ImageViewer")
        case .subagentCards: return .implemented("SubagentRowView")
        case .workflowCard: return .implemented("WorkflowCardView")
        case .taskBoard: return .implemented("TaskBoardView")
        case .questionCells: return .implemented("PendingCards")
        case .compactionSeam: return .implemented("Compaction")
        case .permissionCards: return .implemented("PendingCards")
        case .failureSurface: return .implemented("StatusBandView")
        case .answerlessTurn: return .implemented("answerless")
        case .interruptedTurn: return .implemented("interruptedTurn")
        case .authBanner: return .implemented("authBanner")
        case .followBottom: return .implemented("jumpButton")
        case .transcriptFind: return .implemented("FindBar")
        case .userEcho: return .implemented("echoed")
        case .vimComposer: return .implemented("VimEngine")
        case .slashCompletion: return .implemented("renderCompletion")
        case .slashDispatch: return .implemented("SlashDispatch.decide")
        case .commandCatalog: return .implemented("CommandCatalogWindow")
        case .attachments: return .implemented("AttachmentIntake")
        case .drafts: return .implemented("DraftStore")
        case .sendQueue: return .implemented("Queue")
        case .modelEffortPicker: return .implemented("PillsRow")
        case .unifiedModelChooser: return .implemented("ModelChooserSheet")
        case .modelEffortDisplay: return .implemented("ModelBadge")
        case .ultracodeAura: return .implemented("UltracodeAura")
        case .stopTurn: return .implemented("cancelCurrentTurn")
        case .statusBand: return .implemented("StatusBandView")
        case .usagePanel: return .implemented("UsagePanel")
        case .usageAnalytics: return .implemented("AnalyticsCardRenderer")
        case .sessionSpend: return .implemented("SpendPanelViewController")
        case .toasts: return .implemented("ToastPresenter")
        case .serverManagement: return .implemented("ServersWindow")
        case .tailnetDiscovery:
            return .gap(
                "The Mac types an address by hand. The scan itself is shared (TailnetScanner, TailnetRadar) and macOS can read the tailnet from the tailscale CLI exactly as the GTK client does, so this is work not yet done rather than a platform that cannot.")
        case .connectDiagnosis: return .implemented("diagnose")
        case .serverSignIn: return .implemented("SignInSheet")
        case .serverSelfUpdate: return .implemented("updateStatus")
        case .serverAutoUpdate: return .implemented("AutoUpdateRow")
        case .newChat: return .implemented("NewChatSheet")
        case .newChatPathCompletion: return .implemented("NewChatSheet")
        case .newChatDefaults: return .implemented("renderDefaults")
        case .newChatFailure: return .implemented("NewChatStatusView")
        case .keyboardShortcuts: return .implemented("ShortcutSet")
        case .shortcutCheatsheet: return .implemented("cheatsheet")
        case .gitState: return .implemented("GitPanelViewController")
        case .fileBrowser: return .implemented("FileTreePane")
        case .terminalPane: return .implemented("TerminalPane")
        case .splitPanes: return .implemented("SplitPaneHost")
        case .videoSlot: return .implemented("VideoSlotView")
        case .watchDirectory: return .implemented("WatchBoardView")
        case .watchAccounts: return .implemented("WatchSignInSheet")
        case .browserSlot: return .implemented("WebSlotView")
        case .newPaneChooser: return .implemented("showChooser")
        case .chatDragToPane: return .implemented("onChatDropped")
        case .clickToActivate: return .implemented("pressLanded")
        case .uiScale: return .implemented("UIScale")
        case .typeRamp: return .implemented("MacTheme.Ramp")
        case .themePicker: return .implemented("MacTheme.Chrome")
        case .settingsSurface: return .implemented("PreferencesWindow")
        case .goalControl: return .implemented("setGoal")
        case .firstRunSetup: return .implemented("FirstRunWindow")
        case .demoMode: return .implemented("enterDemoMode")
        case .activityNotifications: return .implemented("MacNotifier")
        case .hapticFeedback: return .partial("MacHaptics", missing: "the trackpad cannot compose: three canned patterns stand in for the recipes, so strength gates which beats survive but never how hard one lands, and a cue is felt only while a hand is on the trackpad")
        case .missedActivity: return .implemented("ActivityInbox.ordered")
        case .homeQuickActions: return .notApplicable("macOS has no Home screen to long-press; the Dock is the OS's own launcher, and the destinations the phone's quick actions reach are one click inside the app's window")
        case .presenceOrb: return .implemented("PresenceOrbView")
        case .gameCenter:
            return .partial(
                "MacGameCenter",
                missing:
                    "the trophy case renders and reports through the same coordinator as iOS, but the dev build is ad-hoc signed without the com.apple.developer.game-center entitlement, so GKLocalPlayer cannot authenticate until the Mac app ships signed; the surface states the unavailability instead of hiding")
        case .projectBoard: return .implemented("toggleProjectScope")
        case .quickAsk: return .implemented("QuickAskPanel")
        case .summonAnywhere: return .implemented("MacSummon")
        case .updateCenter:
            return .partial(
                "UpdateWindowController",
                missing:
                    "every server is asked, classified by Core and installed end to end through its own restart, and the app's own row reads the checkout it was built from — but nothing here installs the app itself: rebuilding the .app takes xcodegen and a multi-minute xcodebuild whose product is the very bundle the process is executing out of, so the row states that obstacle and hands over the exact build command instead, and Update everything covers the servers only")
        }
    }
}
