import TailscodeCore

/// The Mac's answer to every capability in `CapabilityRegistry`. The switch is exhaustive on
/// purpose: a capability added to the registry refuses to compile this client until someone
/// decides what the Mac does about it. One case per line, no `default` — `scripts/parity.sh`
/// parses this file and greps every anchor against `TailscodeMac/`.
enum ParityManifest {
    static let client = ParityClient.mac

    static func evidence(for capability: AppCapability) -> ParityEvidence {
        switch capability {
        case .sessionSections: return .implemented("groupIntoSections")
        case .sessionRowStatus: return .implemented("SessionRowModel")
        case .sessionPinning: return .implemented("menuTogglePinned")
        case .unreadTracking: return .implemented("markUnread")
        case .savedChats: return .implemented("SavedChatStore")
        case .archivedChats: return .implemented("ArchivedChatStore")
        case .deleteSession: return .implemented("deleteSession")
        case .renameSession: return .implemented("renameSession")
        case .forkSession: return .implemented("forkSession")
        case .listFilter: return .implemented("searchField")
        case .autoOpenLastSession: return .implemented("lastSession")
        case .liveListUpdates: return .implemented("SessionListStreaming")
        case .rowContextActions: return .implemented("rowMenu")
        case .rowSnippet: return .implemented("model.snippet ?? model.detail")
        case .usageGauges: return .implemented("usageFooter")
        case .quotaExhaustion: return .implemented("quotaNotice")
        case .markdownRendering: return .implemented("MacMarkdown")
        case .streamingGrowth: return .implemented("applyRows")
        case .streamCascade: return .implemented("CascadePainter")
        case .toolRows: return .implemented("ToolRowView")
        case .toolDiffs: return .implemented("ToolDiff")
        case .compactActivity: return .implemented("ToolRowView.makeRun")
        case .imageParts: return .implemented("ImageStore")
        case .imageViewer: return .implemented("ImageViewer")
        case .subagentCards: return .implemented("SubagentRowView")
        case .workflowCard: return .implemented("WorkflowCardView")
        case .questionCells: return .implemented("PendingCards")
        case .compactionSeam: return .implemented("Compaction")
        case .permissionCards: return .implemented("PendingCards")
        case .failureSurface: return .implemented("StatusBandView")
        case .authBanner: return .implemented("authBanner")
        case .followBottom: return .implemented("jumpButton")
        case .transcriptFind: return .implemented("FindBar")
        case .userEcho: return .implemented("echoed")
        case .vimComposer: return .implemented("VimEngine")
        case .slashCompletion: return .implemented("renderCompletion")
        case .slashDispatch: return .implemented("SlashDispatch.decide")
        case .commandCatalog: return .implemented("CommandCatalogWindow")
        case .attachments: return .implemented("AttachmentIntake")
        case .drafts: return .implemented("tailscode.draft")
        case .sendQueue: return .implemented("Queue")
        case .modelEffortPicker: return .implemented("PillsRow")
        case .unifiedModelChooser: return .implemented("ModelChooserSheet")
        case .modelEffortDisplay: return .implemented("ModelBadge")
        case .ultracodeAura: return .implemented("UltracodeAura")
        case .stopTurn: return .implemented("cancelCurrentTurn")
        case .statusBand: return .implemented("StatusBandView")
        case .usagePanel: return .implemented("UsagePanel")
        case .toasts: return .implemented("ToastPresenter")
        case .serverManagement: return .implemented("ServersWindow")
        case .connectDiagnosis: return .implemented("diagnose")
        case .serverSignIn: return .implemented("SignInSheet")
        case .serverSelfUpdate: return .implemented("updateStatus")
        case .newChat: return .implemented("NewChatSheet")
        case .keyboardShortcuts: return .implemented("ShortcutSet")
        case .shortcutCheatsheet: return .implemented("cheatsheet")
        case .fileBrowser: return .implemented("FileTreePane")
        case .terminalPane: return .implemented("TerminalPane")
        case .splitPanes: return .implemented("SplitPaneHost")
        case .videoSlot: return .implemented("VideoSlotView")
        case .browserSlot: return .implemented("WebSlotView")
        case .newPaneChooser: return .implemented("showChooser")
        case .chatDragToPane: return .implemented("onChatDropped")
        case .clickToActivate: return .implemented("pressLanded")
        case .uiScale: return .implemented("UIScale")
        case .themePicker: return .implemented("MacTheme")
        case .settingsSurface: return .implemented("PreferencesWindow")
        case .goalControl: return .implemented("setGoal")
        case .firstRunSetup: return .implemented("FirstRunWindow")
        case .demoMode: return .implemented("enterDemoMode")
        case .activityNotifications: return .implemented("MacNotifier")
        case .hapticFeedback: return .gap("nothing calls NSHapticFeedbackManager yet; a Force Touch trackpad can tick, but it is only felt while a hand is on it and it takes no strength, so the setting the phone owns has no meaning here until the cues are wired")
        }
    }
}
