#!/usr/bin/env python3
"""Turn Package.resolved into Flatpak sources, because a Flathub build has no network.

Flathub fetches every source before the build and then cuts the network, while SwiftPM resolves its
dependencies by cloning them at build time. The bridge between the two is this: every pin becomes a
declared git source checked out beside the manifest, and the build sets a SwiftPM mirror per package
so the resolve finds each one locally and never reaches for the network at all.

Run it after any dependency change; it re-resolves against the published Kit tag first, since a
Flatpak build resolves that way and a Package.resolved written against the sibling working copy
would be missing the Kit entirely.

    scripts/gen-flatpak-sources.py
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLIENT = ROOT / "TailscodeLinux"
OUT = ROOT / "packaging" / "flatpak" / "generated-sources.json"
MIRRORS = "swiftpm-mirrors"


def resolve_remote() -> dict:
    """Resolve exactly the way the Flatpak build will, in a scratch directory, so this repo's own
    Package.resolved is neither read stale nor overwritten."""
    env = dict(os.environ, TAILSCODE_KIT_REMOTE="1")
    with tempfile.TemporaryDirectory() as scratch:
        subprocess.run(
            ["swift", "package", "resolve", "--scratch-path", scratch],
            cwd=CLIENT, env=env, check=True)
        return json.loads((CLIENT / "Package.resolved").read_text())


def pins(resolved: dict) -> list[dict]:
    return resolved.get("pins") or resolved.get("object", {}).get("pins", [])


def main() -> int:
    before = (CLIENT / "Package.resolved").read_text()
    try:
        resolved = resolve_remote()
    except subprocess.CalledProcessError as error:
        print(f"!! swift package resolve failed ({error.returncode}) — is the Kit tag published?",
              file=sys.stderr)
        return 1

    sources = []
    for pin in sorted(pins(resolved), key=lambda p: p["identity"]):
        state = pin.get("state", {})
        commit = state.get("revision")
        location = pin.get("location")
        if not commit or not location:
            print(f"!! {pin.get('identity')} has no revision or location — skipped", file=sys.stderr)
            continue
        sources.append({
            "type": "git",
            "url": location,
            "commit": commit,
            "dest": f"{MIRRORS}/{pin['identity']}",
        })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(sources, indent=2) + "\n")

    commands = ROOT / "packaging" / "flatpak" / "set-mirrors.sh"
    lines = [
        "#!/bin/sh",
        "# Generated by scripts/gen-flatpak-sources.py — point every dependency at its checkout.",
        "# Run from the flatpak build root, where the app sources and swiftpm-mirrors/ sit together.",
        "set -eu",
    ]
    for pin, source in zip(sorted(pins(resolved), key=lambda p: p["identity"]), sources):
        lines.append(
            f'swift package --package-path TailscodeLinux config set-mirror '
            f'--original {pin["location"]} --mirror "$PWD/{source["dest"]}"')
    commands.write_text("\n".join(lines) + "\n")
    commands.chmod(0o755)

    # The resolve above rewrote the working copy's pins with the remote Kit; put back what the
    # author's tree had, since that file is committed against the sibling checkout.
    (CLIENT / "Package.resolved").write_text(before)

    print(f"wrote {len(sources)} sources to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
