import TailscodeCore

/// The phone's answer to every capability in `CapabilityRegistry`. The switch is exhaustive on
/// purpose: a capability added to the registry refuses to compile this client until someone
/// decides what iOS does about it. One case per line, no `default` — `scripts/parity.sh`
/// parses this file and greps every anchor against `Tailscode/`.
enum ParityManifest {
    static let client = ParityClient.iOS

    static func evidence(for capability: AppCapability) -> ParityEvidence {
        switch capability {
        case .sessionSections: return .implemented("sectionedRows")
        case .sessionRowStatus: return .implemented("statusPill")
        case .activityIconography: return .implemented("ActivityBadgeView")
        case .sessionPinning: return .implemented("togglePinned")
        case .unreadTracking: return .implemented("markUnread")
        case .savedChats: return .implemented("SavedChatsViewController")
        case .archivedChats: return .implemented("ArchivedChatsViewController")
        case .deleteSession: return .implemented("confirmDelete")
        case .bulkSelection: return .implemented("performBulk")
        case .bulkSplit: return .notApplicable("one conversation fills a phone; a selection has no tiling to be spent on, and the same reason splitPanes is not applicable applies to opening several at once")
        case .renameSession: return .implemented("promptRename")
        case .forkSession: return .implemented("forkConversation")
        case .transcriptSearch: return .implemented("TranscriptSearchViewController")
        case .listFilter: return .implemented("filteredEntries")
        case .autoOpenLastSession: return .notApplicable("the phone launches to the Home board by design; Live cards and deep links reopen work")
        case .liveListUpdates: return .implemented("startStreams")
        case .rowContextActions: return .implemented("sessionMenu")
        case .rowSnippet: return .implemented("agentTask")
        case .rowFacets: return .implemented("ageAccessory")
        case .modelIdentityTint: return .implemented("ModelChipText")
        case .usageGauges: return .implemented("QuotaCard")
        case .quotaExhaustion: return .implemented("applyQuotaExhaustion")
        case .quotaScoping: return .implemented("RowMarksView")
        case .markdownRendering: return .implemented("TextBubbleCell")
        case .transcriptLinks: return .implemented("dataDetectorTypes")
        case .syntaxHighlighting: return .implemented("CodeBlockCell.highlightedCode")
        case .streamingGrowth: return .implemented("reconfigureItems")
        case .streamCascade: return .implemented("CascadeDriver")
        case .toolRows: return .implemented("ToolStepRenderer")
        case .toolDiffs: return .implemented("editDiff")
        case .compactActivity: return .implemented("ActivityGroupCell")
        case .imageParts: return .implemented("ImageBubbleCell")
        case .imageViewer: return .implemented("ImageViewerViewController")
        case .subagentCards: return .implemented("SubagentCardCell")
        case .workflowCard: return .implemented("WorkflowCardCell")
        case .taskBoard: return .implemented("TaskBoardCell")
        case .questionCells: return .implemented("QuestionCell")
        case .compactionSeam: return .implemented("CompactionCell")
        case .permissionCards: return .implemented("PermissionCell")
        case .failureSurface: return .implemented("updateBanner")
        case .answerlessTurn: return .implemented("AnswerlessTurnCell")
        case .interruptedTurn: return .implemented("InterruptedTurnCell")
        case .authBanner: return .implemented("presentSignIn")
        case .followBottom: return .implemented("syncFAB")
        case .transcriptFind: return .implemented("runFind")
        case .userEcho: return .implemented("LocalEcho")
        case .vimComposer: return .notApplicable("a touch composer; modal editing presumes a hardware keyboard")
        case .slashCompletion: return .implemented("SlashCommandPalette")
        case .slashDispatch: return .implemented("SlashDispatch.decide")
        case .commandCatalog: return .implemented("CommandCatalogViewController")
        case .attachments: return .implemented("pendingAttachments")
        case .drafts: return .implemented("draftScope")
        case .sendQueue: return .implemented("flushQueue")
        case .modelEffortPicker: return .implemented("modelBarButton")
        case .unifiedModelChooser: return .implemented("ModelChooser")
        case .modelEffortDisplay: return .implemented("displayedModel")
        case .modelCapabilitySurfacing: return .implemented("refreshAttachmentGating")
        case .responseStats: return .implemented("ResponseStatsCell")
        case .ultracodeAura: return .implemented("UltracodeAura")
        case .stopTurn: return .implemented("composerDidTapStop")
        case .statusBand: return .implemented("StatusFacts.from")
        case .usagePanel: return .implemented("UsageViewController")
        case .usageAnalytics: return .implemented("AnalyticsCardRenderer")
        case .deepseekBalance: return .implemented("DeepSeekBalance")
        case .sessionSpend: return .implemented("SpendViewController")
        case .toasts: return .implemented("presentToast")
        case .serverManagement: return .implemented("ConnectionController")
        case .tailnetDiscovery: return .implemented("DiscoveryViewController")
        case .connectDiagnosis: return .implemented("ConnectDiagnosis")
        case .serverSignIn: return .implemented("ServerSignInViewController")
        case .serverSelfUpdate: return .implemented("BridgeUpdater")
        case .serverRestart: return .implemented("confirmRestart")
        case .serverAutoUpdate: return .implemented("UpdateMonitor.setAutoUpdate")
        case .newChat: return .implemented("NewChatViewController")
        case .newChatPathCompletion: return .implemented("NewChatViewController")
        case .newChatDefaults: return .implemented("renderDefaults")
        case .newChatFailure: return .implemented("NewChatStatusView")
        case .keyboardShortcuts: return .implemented("KeyBridge")
        case .shortcutCheatsheet: return .implemented("ShortcutCheatsheetViewController")
        case .fileBrowser: return .implemented("FileBrowserViewController")
        case .gitState: return .implemented("GitStatusViewController")
        case .terminalPane: return .notApplicable("iOS has no shell; the pane presumes the app shares a filesystem with the agent")
        case .browserSlot: return .notApplicable("no tiling on a phone; a page beside the work presumes panes that tile, and the system browser owns the page on iOS")
        case .videoSlot: return .notApplicable("no tiling on a phone; a slot is a pane among panes, and the same reason splitPanes is not applicable applies to what a pane could hold")
        case .watchDirectory: return .notApplicable("the board is what an empty video slot shows instead of a text box, and a phone has no slot to show it in; a full-screen browser of what is on would be a different app, not this capability")
        case .watchAccounts: return .notApplicable("nothing on a phone reads a follow list — there is no board and no slot to put one in, so an account here would sign in to feed a surface that does not exist")
        case .splitPanes: return .notApplicable("one conversation fills a phone; a tiling tree presumes a desktop's width and the OS owns window arrangement")
        case .newPaneChooser: return .notApplicable("no split panes on a phone; a new conversation starts from the chat list, which already spans every server")
        case .chatDragToPane: return .notApplicable("no panes to drag a chat into; the list opens a chat into the one conversation surface a phone has")
        case .clickToActivate: return .notApplicable("a touch has no ambiguity to resolve: one conversation fills the screen, so there is no unfocused pane or second region a tap could mean instead")
        case .uiScale: return .implemented("Theme")
        case .typeRamp: return .implemented("Theme.Ramp")
        case .themePicker: return .implemented("ThemePickerViewController")
        case .settingsSurface: return .implemented("SettingsViewController")
        case .goalControl: return .implemented("updateGoalChip")
        case .firstRunSetup: return .implemented("ServerSetupViewController")
        case .tailscaleReadiness:
            return .partial(
                "TailnetStatus",
                missing:
                    "the phone reads only present-or-absent: a tailnet address or a row that opens "
                    + "the Tailscale app. iOS cannot see whether the daemon is signed out or stopped, "
                    + "so the four states collapse into two and the remedy is always the same tap")
        case .demoMode: return .implemented("enterDemoMode")
        case .activityNotifications: return .implemented("NotificationManager")
        case .missedActivity: return .implemented("MissedActivityCell")
        case .hapticFeedback: return .implemented("HapticEngine")
        case .homeQuickActions: return .implemented("HomeQuickActions")
        case .usageWidgets: return .implemented("WidgetGlance")
        case .presenceOrb: return .implemented("PresenceOrbView")
        case .gameCenter: return .implemented("GameCenterCoordinator")
        case .projectBoard: return .implemented("openProjectBoard")
        case .quickAsk: return .implemented("QuickAskViewController")
        case .summonAnywhere: return .notApplicable("iOS gives no app a key from the whole system — there is no chord to claim and nothing to press it in, since another app is the whole screen; the phone's share of asking from outside the app is the icon's jump list and the Control Center tile, which quickAsk already carries")
        case .updateCenter: return .implemented("UpdateCenterViewController")
        }
    }
}
